# 基础镜像：GraalVM Community JDK25
FROM ghcr.io/graalvm/graalvm-community:25

# 设置工作目录
WORKDIR /app

# 暴露SpringBoot默认端口
EXPOSE 8080

# 安装常用工具
RUN microdnf install -y git curl wget vim tar gzip && microdnf clean all

# 保持容器运行，不自动启动应用
CMD ["sleep", "infinity"]
