services:
  app:
    build:
      context: ..
      dockerfile: devops/Dockerfile.dev
    container_name: longlian-oa-backend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - maven_repo:/root/.m2
    # 让容器保持运行
    stdin_open: true
    tty: true