longlian:
  display-name: "longlian-oa" # 用于展示的系统名称
  datasource:
    type: ${DATASOURCE_TYPE:mysql}  # mysql 或 sqlite
  cache:
    type: ${CACHE_TYPE:redis}       # redis 或 local

spring:
  application:
    name: longlian-oa
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  main:
    allow-circular-references: true

  # MySQL 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    druid:
      initial-size: ${DRUID_INITIAL_SIZE:5}
      max-active: ${DRUID_MAX_ACTIVE:20}
      min-idle: ${DRUID_MIN_IDLE:5}
      max-wait: ${DRUID_MAX_WAIT:60000}
      time-between-eviction-runs-millis: ${DRUID_EVICTION_INTERVAL:60000}
      min-evictable-idle-time-millis: ${DRUID_MIN_EVICTABLE_IDLE:300000}
      validation-query: SELECT 1
      filters: stat,wall,logback
      connection-properties: druid.stat.slowSqlMillis=2000;druid.stat.logSlowSql=true
  # Redis 配置
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:1}
  mail:
    host: ${NOTIFY_HOST}
    username: ${NOTIFY_USERNAME}
    password: ${NOTIFY_PASSWORD}
    port: ${NOTIFY_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: ${MAIL_STARTTLS}
          ssl:
            enable: ${MAIL_SSL}

# SQLite 配置
sqlite:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: ${SQLITE_URL}

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted_at
      logic-delete-value: now()
      logic-not-delete-value: 'null'
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: online.longlian.app.common.handler.CodeEnumTypeHandler
debug: ${APP_DEBUG:false}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    enabled: ${SPRINGDOC_ENABLED:true}
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:true}
  packages-to-scan:
    - online.longlian.app.controller.admin
    - online.longlian.app.controller.user
storage:
  type: ${STORAGE_TYPE:LOCAL}   # LOCAL 或 COS
  local:
    upload-url: ${STORAGE_LOCAL_UPLOAD_URL:}
    base-path: ${STORAGE_LOCAL_BASE_PATH:}
  cos:
    bucket: ${STORAGE_COS_BUCKET:}
    region: ${STORAGE_COS_REGION:}
    secret-id: ${STORAGE_COS_SECRET_ID:}
    secret-key: ${STORAGE_COS_SECRET_KEY:}
    url-prefix: ${STORAGE_COS_URL_PREFIX:}
notify:
  type: EMAIL
  email:
    template:
      path: classpath:templates/verify-code.html
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400
  header: Authorization
  prefix: Bearer