-- 期望 schema 状态（声明式）
-- 修改此文件后执行 task db:diff:描述 生成迁移文件

CREATE TABLE `admin` (id BIGINT NOT NULL, username VARCHAR(64) NOT NULL COMMENT '用户名', password VARCHAR(128) NOT NULL COMMENT '密码', `role` VARCHAR(32) NOT NULL COMMENT '角色：root/normal', last_login_at datetime(0) DEFAULT NOW() NOT NULL COMMENT '上一次登录时间', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_ADMIN PRIMARY KEY (id), UNIQUE (username)) COMMENT='管理员表';

CREATE TABLE base_task (id BIGINT NOT NULL COMMENT '原子任务ID', org_id BIGINT NOT NULL COMMENT '所属组织ID', name VARCHAR(100) NOT NULL COMMENT '任务名称（标题）（如：创建/翻译/校对）', icon_file_id BIGINT NULL COMMENT '图标标识', `description` VARCHAR(500) DEFAULT '' NULL COMMENT '任务说明（简介）', meta_schema JSON NULL COMMENT '元数据字段定义(JSON数组)', status TINYINT(3) DEFAULT 1 NOT NULL COMMENT '状态 1-启用 0-禁用', creator_id BIGINT NOT NULL COMMENT '创建人ID', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_BASE_TASK PRIMARY KEY (id)) COMMENT='原子任务表（最小任务单元）';

CREATE TABLE email_verify_otp (id BIGINT NOT NULL COMMENT '邮箱验证码ID', otp_id BIGINT NOT NULL COMMENT '关联验证码ID', receiver VARCHAR(255) NOT NULL COMMENT '接收者邮箱', business_type TINYINT(3) DEFAULT 0 NOT NULL COMMENT '业务类型 0-登录 1-注册 2-忘记密码', send_status TINYINT(3) DEFAULT 0 NOT NULL COMMENT '发送状态 0-待发送 1-发送成功 2-发送失败', sent_at datetime(0) NULL COMMENT '发送成功时间', failed_at datetime(0) NULL COMMENT '发送失败时间', fail_reason VARCHAR(500) DEFAULT '' NOT NULL COMMENT '发送失败原因', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_EMAIL_VERIFY_OTP PRIMARY KEY (id)) COMMENT='邮箱验证码扩展表';

CREATE TABLE group_application (id BIGINT NOT NULL, org_id BIGINT NOT NULL COMMENT '目标组织ID', user_id BIGINT NOT NULL COMMENT '申请人ID', status TINYINT(3) DEFAULT 0 NOT NULL COMMENT '状态：0-待审核 1-通过 2-拒绝', reviewer_id BIGINT NULL COMMENT '审核人ID', reviewed_at datetime(0) NULL COMMENT '审核时间', review_remark VARCHAR(500) DEFAULT '' NULL COMMENT '审核备注', application_type TINYINT(3) NULL COMMENT '申请入组的类型：0-注册入组 1-已注册用户入组', username VARCHAR(50) NULL COMMENT '用户名', password VARCHAR(100) NULL COMMENT '密码', nickname VARCHAR(50) DEFAULT '' NULL COMMENT '昵称', email VARCHAR(100) DEFAULT '' NULL COMMENT '邮箱', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_GROUP_APPLICATION PRIMARY KEY (id)) COMMENT='入组申请表';

CREATE TABLE item (id BIGINT NOT NULL, project_id BIGINT NOT NULL COMMENT '所属企划ID', title VARCHAR(100) NOT NULL COMMENT '项目名称', task_template_id BIGINT NOT NULL COMMENT '创建时关联的任务模板ID（仅记录溯源）', status TINYINT(3) DEFAULT 1 NOT NULL COMMENT '状态 1-进行中 2-已完成 3-已公布', creator_id BIGINT NOT NULL COMMENT '创建人ID', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_ITEM PRIMARY KEY (id)) COMMENT='项目表';

CREATE TABLE item_task_flow (id BIGINT NOT NULL COMMENT '项目任务流ID', item_id BIGINT NOT NULL COMMENT '所属项目ID', project_id BIGINT NOT NULL COMMENT '所属企划ID', task_template_id BIGINT NOT NULL COMMENT '关联任务模板ID', name VARCHAR(100) NOT NULL COMMENT '任务流名称（继承自任务模板）', `description` VARCHAR(500) DEFAULT '' NULL COMMENT '任务流说明', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_ITEM_TASK_FLOW PRIMARY KEY (id), UNIQUE (item_id)) COMMENT='项目任务流表';

CREATE TABLE item_task_node (id BIGINT NOT NULL COMMENT '项目任务节点ID', item_task_flow_id BIGINT NOT NULL COMMENT '所属项目任务流ID', item_id BIGINT NOT NULL COMMENT '所属项目ID', project_id BIGINT NOT NULL COMMENT '所属企划ID', base_task_id BIGINT NOT NULL COMMENT '关联原子任务ID', name VARCHAR(100) NOT NULL COMMENT '任务名称', meta_schema JSON NULL COMMENT '节点元数据字段定义快照(JSON数组)', sort INT DEFAULT 0 NOT NULL COMMENT '步骤顺序', parallel_sort INT NULL COMMENT '并行组号排序', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_ITEM_TASK_NODE PRIMARY KEY (id)) COMMENT='项目任务节点表';

CREATE TABLE one_time_password (id BIGINT UNSIGNED NOT NULL, code VARCHAR(128) NOT NULL COMMENT '验证码', expired_at datetime(0) NOT NULL COMMENT '过期时间', used_at datetime(0) NULL COMMENT '使用时间', biz_type TINYINT(3) NOT NULL COMMENT '业务类型 1-邀请创建组织 2-邀请加入组织 3-邮箱验证码', status TINYINT(3) NOT NULL COMMENT '状态 0-待使用 1-已使用', creator_id BIGINT NOT NULL COMMENT '创建者 ID', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT NOW() NULL, CONSTRAINT PK_ONE_TIME_PASSWORD PRIMARY KEY (id)) COMMENT='一次性密码（otp）表';

CREATE TABLE `organization` (id BIGINT NOT NULL COMMENT '组织ID', name VARCHAR(100) NOT NULL COMMENT '组织名称', avatar_file_id BIGINT NULL COMMENT '组织头像', `description` VARCHAR(500) DEFAULT '' NULL COMMENT '组织简介', status TINYINT(3) DEFAULT 1 NOT NULL COMMENT '状态 1-启用 0-禁用', creator_id BIGINT NOT NULL COMMENT '创建人ID', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_ORGANIZATION PRIMARY KEY (id)) COMMENT='组织表';

CREATE TABLE organization_create_otp (id BIGINT NOT NULL COMMENT '邀请ID', otp_id BIGINT NOT NULL COMMENT '关联验证码ID', invited_user_id BIGINT NULL COMMENT '被邀请用户ID', org_id BIGINT NULL COMMENT '创建成功后的组织ID', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_ORGANIZATION_CREATE_OTP PRIMARY KEY (id)) COMMENT='邀请创建组织表';

CREATE TABLE organization_join_otp (id BIGINT NOT NULL COMMENT '邀请ID', otp_id BIGINT NOT NULL COMMENT '关联验证码ID', org_id BIGINT NOT NULL COMMENT '目标组织ID', invited_user_id BIGINT NULL COMMENT '被邀请用户ID', org_member_id BIGINT NULL COMMENT '加入成功后的组织成员ID', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_ORGANIZATION_JOIN_OTP PRIMARY KEY (id)) COMMENT='邀请加入组织表';

CREATE TABLE organization_member (id BIGINT NOT NULL, org_id BIGINT NOT NULL COMMENT '组织ID', user_id BIGINT NOT NULL COMMENT '用户ID', org_role VARCHAR(20) DEFAULT 'ORG_USER' NOT NULL COMMENT '组织内角色：ORG_ADMIN/ORG_USER', joined_at datetime(0) DEFAULT NOW() NOT NULL COMMENT '入组时间', last_submitted_at datetime(0) NULL COMMENT '上次提交任务时间', submit_count INT DEFAULT 0 NOT NULL COMMENT '任务提交总数', status TINYINT(3) DEFAULT 1 NOT NULL COMMENT '状态 1-启用 0-禁用', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_ORGANIZATION_MEMBER PRIMARY KEY (id)) COMMENT='组织成员表';

CREATE TABLE permission (id BIGINT NOT NULL COMMENT '权限ID', perm_code VARCHAR(100) NOT NULL COMMENT '权限编码（如：org:member:disable）', perm_name VARCHAR(50) NOT NULL COMMENT '权限名称', perm_type TINYINT(3) NOT NULL COMMENT '类型 1-菜单 2-按钮 3-接口', `path` VARCHAR(200) DEFAULT '' NULL COMMENT '前端路由/接口路径', parent_id BIGINT DEFAULT 0 NULL COMMENT '父权限ID（用于菜单层级）', sort INT DEFAULT 0 NULL COMMENT '排序（前端展示顺序）', status TINYINT(3) DEFAULT 1 NOT NULL COMMENT '状态 1-启用 0-禁用', created_at datetime(0) DEFAULT NOW() NOT NULL COMMENT '创建时间', updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', deleted_at datetime(0) NULL COMMENT '软删除时间', CONSTRAINT PK_PERMISSION PRIMARY KEY (id), UNIQUE (perm_code)) COMMENT='权限表';

CREATE TABLE project (id BIGINT NOT NULL, org_id BIGINT NOT NULL COMMENT '所属组织ID', type_id BIGINT NOT NULL COMMENT '企划类型ID', title VARCHAR(100) NOT NULL COMMENT '企划名称', alias VARCHAR(100) DEFAULT '' NULL COMMENT '别名', metadata JSON NULL COMMENT '扩展信息(JSON字符串)', cover_file_id BIGINT NULL COMMENT '封面图', `description` TEXT NULL COMMENT '简介', status TINYINT(3) DEFAULT 1 NOT NULL COMMENT '状态 1-进行中 2-已完成 3-已归档', creator_id BIGINT NOT NULL COMMENT '创建人ID', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_PROJECT PRIMARY KEY (id)) COMMENT='企划表';

CREATE TABLE project_type (id BIGINT NOT NULL COMMENT '企划类型ID', org_id BIGINT NOT NULL COMMENT '所属组织ID', name VARCHAR(50) NOT NULL COMMENT '类型名称（如：漫画/小说/美术/视频）', status TINYINT(3) DEFAULT 1 NOT NULL COMMENT '状态 1-启用 0-禁用', creator_id BIGINT NOT NULL COMMENT '创建人ID', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_PROJECT_TYPE PRIMARY KEY (id)) COMMENT='企划类型表';

CREATE TABLE project_workshop (id BIGINT NOT NULL, project_id BIGINT NOT NULL COMMENT '企划ID', user_id BIGINT NOT NULL COMMENT '添加人ID', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_PROJECT_WORKSHOP PRIMARY KEY (id)) COMMENT='企划-工坊关联表（用户添加企划）';

CREATE TABLE `resource` (id BIGINT NOT NULL COMMENT '文件ID', org_id BIGINT NOT NULL COMMENT '所属组织ID', storage_type TINYINT(3) NOT NULL COMMENT '存储类型 1-本地存储 2-云对象存储', storage_key VARCHAR(255) NOT NULL COMMENT '存储唯一标识（如OSS的objectKey/本地文件路径）', file_name VARCHAR(255) NOT NULL COMMENT '原始文件名', file_ext VARCHAR(20) NOT NULL COMMENT '文件扩展名', file_size BIGINT DEFAULT 0 NOT NULL COMMENT '文件大小', file_mime VARCHAR(100) DEFAULT '' NULL COMMENT '文件MIME类型', biz_type VARCHAR(50) NOT NULL COMMENT '业务类型（如：avatar/cover/task_submit）', biz_id BIGINT NOT NULL COMMENT '业务ID（关联的用户ID/组织ID/企划ID/任务提交ID）', process_status TINYINT(3) DEFAULT 0 NOT NULL COMMENT '状态 0-未上传 1-已上传 3-已废弃', creator_id BIGINT NOT NULL COMMENT '上传人ID', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_RESOURCE PRIMARY KEY (id)) COMMENT='通用文件存储表';

CREATE TABLE `role` (id BIGINT NOT NULL COMMENT '角色ID', role_code VARCHAR(50) NOT NULL COMMENT '角色编码（如：ORG_ADMIN）', role_name VARCHAR(50) NOT NULL COMMENT '角色名称', `description` VARCHAR(200) DEFAULT '' NULL COMMENT '角色描述', status TINYINT(3) DEFAULT 1 NOT NULL COMMENT '状态 1-启用 0-禁用', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_ROLE PRIMARY KEY (id), UNIQUE (role_code)) COMMENT='角色表';

CREATE TABLE role_permission (id BIGINT NOT NULL COMMENT '主键ID', role_id BIGINT NOT NULL COMMENT '角色ID', permission_id BIGINT NOT NULL COMMENT '权限ID', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_ROLE_PERMISSION PRIMARY KEY (id)) COMMENT='角色权限关联表';

CREATE TABLE scheduled_task_log (id BIGINT NOT NULL COMMENT '日志ID', task_name VARCHAR(100) NOT NULL COMMENT '任务名称', trigger_source TINYINT(3) NOT NULL COMMENT '触发来源 1-SCHEDULED(定时触发) 2-MANUAL(手动触发)', execute_time_param datetime(0) NOT NULL COMMENT '上层传递的执行时间', status TINYINT(3) NOT NULL COMMENT '执行状态 1-RUNNING(执行中) 2-SUCCESS(成功) 3-FAILED(失败)', error_message TEXT NULL COMMENT '失败时的错误信息', execution_id VARCHAR(64) NOT NULL COMMENT '执行追踪ID', triggered_by BIGINT NULL COMMENT '手动触发人ID（定时触发时为NULL）', started_at datetime(0) NOT NULL COMMENT '开始执行时间', ended_at datetime(0) NULL COMMENT '结束执行时间', duration_ms BIGINT NULL COMMENT '执行耗时（毫秒）', created_at datetime(0) DEFAULT NOW() NOT NULL COMMENT '创建时间', updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', deleted_at datetime(0) NULL COMMENT '软删除时间', CONSTRAINT PK_SCHEDULED_TASK_LOG PRIMARY KEY (id)) COMMENT='定时任务执行日志表';

CREATE TABLE task_instance (id BIGINT NOT NULL, project_id BIGINT NOT NULL COMMENT '所属企划ID', item_id BIGINT NOT NULL COMMENT '所属项目ID', item_task_node_id BIGINT NOT NULL COMMENT '关联项目任务节点ID', task_flow_id BIGINT NOT NULL COMMENT '关联任务流ID', assignee_id BIGINT NULL COMMENT '接取人ID', status TINYINT(3) DEFAULT 1 NOT NULL COMMENT '任务状态 1-PENDING(待接取) 2-CLAIMED(待提交) 3-COMPLETED(已完成)', submitted_at datetime(0) NULL COMMENT '提交时间', completed_at datetime(0) NULL COMMENT '完成时间', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_TASK_INSTANCE PRIMARY KEY (id)) COMMENT='任务实例表';

CREATE TABLE task_submission (id BIGINT NOT NULL, project_id BIGINT NOT NULL COMMENT '所属企划ID', item_id BIGINT NOT NULL COMMENT '所属项目ID', task_instance_id BIGINT NOT NULL COMMENT '所属任务实例ID', item_task_node_id BIGINT NOT NULL COMMENT '关联项目任务节点ID', submitter_id BIGINT NOT NULL COMMENT '提交人ID', metadata JSON NULL COMMENT '提交元数据(JSON对象，按节点 meta_schema 组织)', status TINYINT(3) DEFAULT 1 NOT NULL COMMENT '提交状态 1-SUBMITTED(已提交) 2-REJECTED(已打回) 3-RESET(已重置)', reviewer_id BIGINT NULL COMMENT '审核人ID（打回操作人）', reviewed_at datetime(0) NULL COMMENT '审核/打回时间', review_comment VARCHAR(500) DEFAULT '' NULL COMMENT '审核/打回意见', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_TASK_SUBMISSION PRIMARY KEY (id)) COMMENT='任务提交记录表';

CREATE TABLE task_template (id BIGINT NOT NULL COMMENT '任务模板ID', org_id BIGINT NOT NULL COMMENT '所属组织ID', name VARCHAR(100) NOT NULL COMMENT '任务模板名称', `description` VARCHAR(500) DEFAULT '' NULL COMMENT '模板说明', status TINYINT(3) DEFAULT 1 NOT NULL COMMENT '状态 1-启用 0-禁用', scope TINYINT(3) DEFAULT 1 NOT NULL COMMENT '1-个人模板 2-组织通用模板', ref_count INT DEFAULT 0 NOT NULL COMMENT '关联的项目数', creator_id BIGINT NOT NULL COMMENT '创建人ID', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_TASK_TEMPLATE PRIMARY KEY (id)) COMMENT='任务模板表';

CREATE TABLE task_template_node (id BIGINT NOT NULL COMMENT '任务模板节点ID', task_template_id BIGINT NOT NULL COMMENT '所属任务模板ID', base_task_id BIGINT NOT NULL COMMENT '关联原子任务ID', sort INT DEFAULT 0 NOT NULL COMMENT '步骤顺序', parallel_sort INT NULL COMMENT '并行组号排序', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_TASK_TEMPLATE_NODE PRIMARY KEY (id)) COMMENT='任务模板节点表';

CREATE TABLE token_blacklist (id BIGINT NOT NULL COMMENT '主键ID', token VARCHAR(512) NOT NULL COMMENT 'Token字符串', token_type TINYINT(3) NOT NULL COMMENT 'Token类型 1-用户端 2-管理端', user_id BIGINT NOT NULL COMMENT '用户/管理员ID', reason VARCHAR(200) DEFAULT '' NULL COMMENT '加入黑名单原因', expired_at datetime(0) NOT NULL COMMENT 'Token过期时间', created_at datetime(0) DEFAULT NOW() NOT NULL COMMENT '创建时间', updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', CONSTRAINT PK_TOKEN_BLACKLIST PRIMARY KEY (id), UNIQUE (token)) COMMENT='Token黑名单表';

CREATE TABLE user (id BIGINT NOT NULL COMMENT '用户ID', username VARCHAR(50) NOT NULL COMMENT '用户名（登录用）', password VARCHAR(100) NOT NULL COMMENT '密码（加密存储）', nickname VARCHAR(50) DEFAULT '' NOT NULL COMMENT '昵称（展示用）', email VARCHAR(100) DEFAULT '' NOT NULL COMMENT '邮箱（登录/通知）', avatar_file_id BIGINT NULL COMMENT '用户头像', default_org_id BIGINT DEFAULT 0 NOT NULL COMMENT '默认组织ID', status TINYINT(3) DEFAULT 1 NOT NULL COMMENT '状态 1-启用 0-禁用', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_USER PRIMARY KEY (id), UNIQUE (username), UNIQUE (email)) COMMENT='系统用户表';

CREATE TABLE user_operation_log (id BIGINT NOT NULL, user_id BIGINT NOT NULL COMMENT '操作人ID', project_id BIGINT NOT NULL COMMENT '所属企划ID', item_id BIGINT NULL COMMENT '所属项目ID', operation_type TINYINT(3) NOT NULL COMMENT '操作类型 1-TASK_CLAIM(接取任务) 2-TASK_SUBMIT(提交任务) 3-TASK_ABANDON(放弃任务) 4-TASK_REJECT(打回任务) 5-TASK_RESET(重置任务) 6-FILE_DOWNLOAD(下载任务)', request_body JSON NULL COMMENT '操作请求体', created_at datetime(0) DEFAULT NOW() NOT NULL COMMENT '操作时间', updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_USER_OPERATION_LOG PRIMARY KEY (id)) COMMENT='用户操作记录表';

CREATE TABLE user_role (id BIGINT NOT NULL COMMENT '主键ID', user_id BIGINT NOT NULL COMMENT '用户ID', role_id BIGINT NOT NULL COMMENT '角色ID', created_at datetime(0) DEFAULT NOW() NOT NULL, updated_at datetime(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, deleted_at datetime(0) NULL, CONSTRAINT PK_USER_ROLE PRIMARY KEY (id)) COMMENT='用户角色关联表';

-- 唯一约束
ALTER TABLE organization_member ADD CONSTRAINT uk_org_member_user UNIQUE (org_id, user_id);
ALTER TABLE role_permission ADD CONSTRAINT uk_role_perm UNIQUE (role_id, permission_id);
ALTER TABLE user_role ADD CONSTRAINT uk_user_role UNIQUE (user_id, role_id);

-- 索引
CREATE INDEX idx_code_expired_at ON one_time_password(code, expired_at);
CREATE INDEX idx_expired ON token_blacklist(expired_at);
CREATE INDEX idx_flow_sort ON item_task_node(item_task_flow_id, sort);
CREATE INDEX idx_org_type ON project(org_id, type_id);
CREATE INDEX idx_receiver_send_status_created_at ON email_verify_otp(receiver, send_status, created_at);
CREATE INDEX idx_started_at ON scheduled_task_log(started_at);
CREATE INDEX idx_task_name ON scheduled_task_log(task_name);
CREATE INDEX idx_user ON token_blacklist(token_type, user_id);
