name: API Tests

on:
  push:
    branches: [ main, release/v1.0.0 ]
  pull_request:
    branches: [ main, release/v1.0.0 ]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
              ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Task
        uses: go-task/setup-task@v2

      - name: Run API Tests
        run: task api-test-docker

      - name: Report results to DeepSource
        run: |
          echo $DEEPSOURCE_COMMIT_SHA
          # 安装CLI
          curl -fsSL https://cli.deepsource.com/install | BINDIR=./bin sh

          # 上报数据
          ./bin/deepsource report --analyzer test-coverage --key java --value-file app/target/site/jacoco/jacoco.xml
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}